name: Prod react deployment

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: self-hosted
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy build files
        run: |
          sudo cp -r dist/* /home/ec2-user/testRepo/testRepoStage

      - name: Restart Nginx
        run: sudo systemctl reload nginx
