name: React CI

# Trigger workflow on push to main or pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Use a self-hosted runner
jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (replace version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build project
      - name: Build project
        run: npm run build
        working-directory: ./

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
        name: dist
        path: ./dist

      # Step 6: Restart ngin
      - name: Restart Nginx
        run: sudo systemctl reload nginx
